trigger:
  branches:
    include:
    - release/*

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  name: npm_core
  inputs:
    command: 'install'
    workingDir: 'Gotho.BlazorPdf/'

- task: Npm@1
  name: npm_mud
  inputs:
    command: 'install'
    workingDir: 'Gotho.BlazorPdf.MudBlazor/'

- task: UseDotNet@2
  name: net9_install
  inputs:
    packageType: 'sdk'
    version: '9.x'

- task: DotNetCoreCLI@2
  name: restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  name: build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--no-restore -c Release'

- task: DotNetCoreCLI@2
  name: pack_core
  inputs:
    command: 'pack'
    packagesToPack: '**/Gotho.BlazorPdf.csproj'
    includesymbols: false
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  name: pack_mud
  inputs:
    command: 'pack'
    packagesToPack: '**/Gotho.BlazorPdf.MudBlazor.csproj'
    includesymbols: false
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  name: publish
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'